# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"


    filter_sets:
        
        squared_thumbnail_medium:
            filters:
                thumbnail:
                    size: [ 140, 140 ]
                    mode: outbound
                    allow_upscale: true
                    

    
        squared_thumbnail_small:
            filters:
               thumbnail:
                    size: [ 120, 120 ]
                    mode: outbound
                    allow_upscale: true



        long_thumbnail_medium:
            filters:
               thumbnail:
                    size: [ 300, 175 ]
                    mode: outbound
                    allow_upscale: true


        long_thumbnail_small:
            filters:
               thumbnail:
                    size: [ 200, 140 ]
                    mode: outbound
                    allow_upscale: true
                background: 
                    size: [ 204, 144 ]
                    position: center
                    color: RGBa(235,0,0,1)