vich_uploader:
    db_driver: orm

    mappings:
       extrait_photo:
           uri_prefix: /uploads/extraits
           upload_destination: '%kernel.project_dir%/public/uploads/extraits'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
