vich_uploader:
    db_driver: orm

    mappings:
       extrait_photo:
           uri_prefix: /uploads/extraits
           upload_destination: '%kernel.project_dir%/public/uploads/extraits'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           
        extrait_morceau:
            uri_prefix: /uploads/sons
            upload_destination: '%kernel.project_dir%/public/uploads/sons'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
